name: Releases
on: 
  push:
    tags:
    - 'v*'

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --release
    - name: Run tests
      run: cargo test --verbose
    - uses: ncipollo/release-action@v1
      with:
        artifacts: "target/release/*"
        token: ${{ secrets.GITHUB_TOKEN }}
